name: process-dotnet-test-results

description: |
  Action that parses .trx reports and creates a status check or PR comment with the results.
  Tests are not run as part of these action.
  The results can be seen on the workflow run or a PR.  One check is created per trx report.

inputs:
  github-token:
    description: 'Used for the GitHub Checks API.  Generally secrets.GITHUB_TOKEN.'
    required: true
  base-directory:
    description: 'The base directory of where to look for .trx files.  Defaults to the root directory of the repository.'
    required: false
  ignore-test-failures:
    description: 'When set to true the status check is set to neutral when there are test failures and it will not block pull requests.'
    required: false
    default: 'false'
  create-status-check:
    description: 'Flag indicating whether a status check with test results should be generated.'
    required: true
    default: 'true'
  create-pr-comment:
    description: 'Flag indicating whether a PR comment with test results should be generated.   When `true` the default behavior is to update an existing comment if one exists.'
    required: true
    default: 'true'
  create-results-file:
    description: 'Flag indicating whether a results file in markdown should be generated.'
    required: false
    default: 'false'
  update-comment-if-one-exists:
    description: 'When `create-pr-comment` is true, this flag determines whether a new comment is created or if the action updates an existing comment if one is found which is the default behavior.'
    required: true
    default: 'true'
  timezone:
    description: 'IANA time zone name (e.g. America/Denver) to display dates in.  If timezone is not provided, dates will be shown in UTC.'
    required: false
  comment-identifier:
    description: 'Used when there are multiple test projects that run separately but are part of the same CI run.'
    required: false
  report-title-filter:
    description: 'Sets the report title in markdown to the `Unit Test Name`. This splits the Unit Test Name by `.` and gets the next word in the name that was inputed in this field.'
    required: false

outputs:
  test-outcome:
    description: 'Test outcome based on presence of failing tests: Failed|Passed.  If exceptions are thrown or if it exits early because of argument errors, this is set to Failed.'
  trx-files:
    description: 'List of trx files that were processed'
  test-results-truncated:
    description: 'Boolean if test results was truncated due to markdown exceeding character limit of 65535.'
  test-results-file-path:
    description: 'File path of the test outcome in markdown format.  This is the same output that is posted in the PR comment'
  status-check-id:
    description: 'The ID of the status check that was created.  This is only set if `create-status-check` is true and a status check was created successfully.'
  pr-comment-id:
    description: 'The ID of the PR comment that was created.  This is only set if `create-pr-comment` is true and a PR was created successfully.'

runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'dist/cleanup.js'
